export const SUBJECTS = [
    { id: "cs101", name: "Introduction to Information Technology", credits: 3 },
    { id: "prog102", name: "Programming Fundamentals", credits: 4 },
    { id: "ds103", name: "Data Structures and Algorithms", credits: 4 },
    { id: "db104", name: "Database Management Systems", credits: 4 },
    { id: "os105", name: "Operating Systems", credits: 3 },
    { id: "cn106", name: "Computer Networks", credits: 3 },
    { id: "web107", name: "Web Development Fundamentals", credits: 3 },
    { id: "ai108", name: "Artificial Intelligence Basics", credits: 3 },
    { id: "ml109", name: "Machine Learning for IT Practitioners", credits: 3 },
    { id: "iot110", name: "Internet of Things (IoT)", credits: 3 },
    { id: "pm111", name: "IT Project Management", credits: 3 },
    { id: "sec112", name: "Network and Cybersecurity", credits: 3 },
    { id: "dm113", name: "Discrete Mathematics for Computing", credits: 3 },
    { id: "sa114", name: "Software Architecture and Design", credits: 3 },
    { id: "ux115", name: "User Experience and Interface Design", credits: 3 },
    { id: "mob116", name: "Mobile App Development", credits: 3 },
    { id: "bigdata117", name: "Big Data Analytics", credits: 3 },
    { id: "par118", name: "Parallel and Distributed Computing", credits: 3 },
    { id: "cloud119", name: "Cloud Computing Essentials", credits: 3 },
    { id: "qa120", name: "Quality Assurance and Testing", credits: 3 },
    { id: "startup121", name: "Entrepreneurship in IT", credits: 3 },
    { id: "int122", name: "Professional Internship", credits: 9 },
    { id: "capstone123", name: "Capstone Project", credits: 6 },
    { id: "calc124", name: "Calculus for IT Professionals", credits: 3 },
    { id: "stats125", name: "Probability and Statistics for IT", credits: 3 },
    { id: "ai126", name: "AI and ChatGPT for IT Professionals", credits: 3 },
    { id: "gpt127", name: "Generative AI and Automation", credits: 3 },
];
